### ISSUE TITLE
[FEATURE] Automate typedoc updates using GitHub actions

### ISSUE THREAD

**Issue by asos-craigmorten** [asos-craigmorten/opine#29]
# Issue

Create a GitHub action to create and merge updates to the typedocs.

## Details

Currently typedoc creation is a manual process which pollutes the PR with dozens of files and detracts from the main work.

This task is to create a GitHub action workflow which is triggered on merges to `main` which will subsequent update the typedocs and merge them in as a subsequent commit.

As a sketch (not tested):

```yaml
name: Publish TypeDocs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Deno v1.1.1
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.1.1
      - run: make typedoc
      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'publish typedocs'
```

REF: https://github.com/github-actions-x/commit

There may be better actions on the marketplace - this was just the first one I found on google.

Notes:
- Need to ensure the `_config.yaml` is preserved.
- Need to make sure the docs are formatted using `make fmt` - some generated files fail the `deno fmt --check` check.
- Should update the `make typedoc` command to include `--name opine`
- Will need to add steps to install typescript and typedoc NPM packages
- Investigate whether any of this is available via `deno` CLI commands.
